import Link from 'next/link';
import React, { useEffect, useState } from 'react';
import { FaBed, FaRulerCombined, FaUserFriends } from 'react-icons/fa';
const money = new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 });
export default function RoomList({ rooms = [] }) {
  const [page,setPage]=useState(1); const perPage=6; const total=Math.ceil(rooms.length/perPage); const shown=rooms.slice((page-1)*perPage,page*perPage);
  useEffect(()=>setPage(1),[rooms]); const go=(number)=>{setPage(number);document.getElementById('room-results')?.scrollIntoView({behavior:'smooth',block:'start'})};
  if(!rooms.length)return <div className='ls-room-empty'><span>0</span><h3>No rooms match those choices</h3><p>Reset the filters or increase your maximum nightly rate.</p></div>;
  return <section className='ls-results' id='room-results'><div className='ls-results-bar'><p><b>{rooms.length}</b> stays selected for you</p><span>Prices shown per night</span></div><div className='ls-results-grid'>{shown.map((room,index)=><article className='ls-result-card' key={room.id||room.room_slug} style={{'--delay':`${index*70}ms`}}><Link href={`/rooms/${room.room_slug}`} className='ls-result-image'><img src={room?.room_images?.[0]?.url||'/images/jpeg/room-1.jpeg'} alt={room.room_name}/><div className='ls-result-overlay'/><span className={`ls-room-status is-${room.room_status}`}>{room.room_status}</span><span className='ls-result-type'>{room.room_type}</span></Link><div className='ls-result-content'><div className='ls-result-title'><h3>{room.room_name}</h3><p><b>{money.format(room.room_price||0)}</b> / night</p></div><p className='ls-result-description'>{room.room_description?.slice(0,125)||'A considered room for a calm and comfortable stay.'}{room.room_description?.length>125?'...':''}</p><div className='ls-result-facts'><span><FaUserFriends/>{room.room_capacity} guests</span><span><FaRulerCombined/>{room.room_size} sqft</span><span><FaBed/>{room.room_type}</span></div><Link href={`/rooms/${room.room_slug}`} className='ls-result-link'>View room <span>&rarr;</span></Link></div></article>)}</div>{total>1&&<nav className='ls-room-pagination' aria-label='Room result pages'><button type='button' disabled={page===1} onClick={()=>go(page-1)}>&larr;</button>{Array.from({length:total},(_,i)=>i+1).map((number)=><button type='button' key={number} className={number===page?'is-active':''} onClick={()=>go(number)}>{number}</button>)}<button type='button' disabled={page===total} onClick={()=>go(page+1)}>&rarr;</button></nav>}</section>;
}