import React, { useEffect, useMemo, useState } from 'react';
import { FaBed, FaCrown, FaHome, FaPaw, FaUserFriends, FaUtensils } from 'react-icons/fa';
const money = new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 });
export default function RoomFilter({ ourRooms = [], setOurFilteredRooms, resultCount = 0 }) {
  const maximum = useMemo(() => Math.max(500000, ...ourRooms.map((room) => Number(room.room_price || 0))), [ourRooms]);
  const [priceRange, setPriceRange] = useState(maximum); const [roomType, setRoomType] = useState('all'); const [breakfast, setBreakfast] = useState(false); const [pets, setPets] = useState(false);
  useEffect(() => { setPriceRange(maximum); }, [maximum]);
  useEffect(() => { let next=[...ourRooms]; if(roomType!=='all') next=next.filter((room)=>room.room_type===roomType); next=next.filter((room)=>Number(room.room_price)<=priceRange); if(breakfast) next=next.filter((room)=>room.provide_breakfast); if(pets) next=next.filter((room)=>room.allow_pets); setOurFilteredRooms(next); }, [roomType,priceRange,breakfast,pets,ourRooms,setOurFilteredRooms]);
  const types=[{value:'all',label:'All',icon:<FaHome/>},{value:'single',label:'Single',icon:<FaBed/>},{value:'couple',label:'Couple',icon:<FaUserFriends/>},{value:'family',label:'Family',icon:<FaUserFriends/>},{value:'presidential',label:'Presidential',icon:<FaCrown/>}];
  const clear=()=>{setRoomType('all');setPriceRange(maximum);setBreakfast(false);setPets(false)}; const active=roomType!=='all'||priceRange<maximum||breakfast||pets;
  return <div className='ls-room-filter'><div className='ls-filter-top'><div><b>Refine your stay</b><span>{resultCount} {resultCount===1?'room':'rooms'} available</span></div><button type='button' onClick={clear} disabled={!active}>Reset filters</button></div><div className='ls-filter-body'><div className='ls-filter-group ls-filter-types'><label>Room style</label><div>{types.map((type)=><button type='button' key={type.value} className={roomType===type.value?'is-active':''} onClick={()=>setRoomType(type.value)}>{type.icon}<span>{type.label}</span></button>)}</div></div><div className='ls-filter-group ls-price-filter'><label><span>Maximum nightly rate</span><b>{money.format(priceRange)}</b></label><input type='range' min='20000' max={maximum} step='1000' value={priceRange} onChange={(event)=>setPriceRange(Number(event.target.value))}/><div><span>{money.format(20000)}</span><span>{money.format(maximum)}</span></div></div><div className='ls-filter-group ls-amenity-filter'><label>Preferences</label><div><button type='button' className={breakfast?'is-active':''} onClick={()=>setBreakfast(!breakfast)}><FaUtensils/> Breakfast</button><button type='button' className={pets?'is-active':''} onClick={()=>setPets(!pets)}><FaPaw/> Pet friendly</button></div></div></div></div>;
}